#
#--------------------------------------------------------------------------
# golang 1.25 trixie
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION=1.25
FROM golang:${GOLANG_VERSION}-trixie
LABEL maintainer="chinayin <whereismoney@qq.com>"

COPY prebuildfs /
