#
#--------------------------------------------------------------------------
# golang 1.25 trixie
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}-trixie
LABEL maintainer="chinayin <whereismoney@qq.com>"

#COPY prebuildfs /
