#
#--------------------------------------------------------------------------
# golang 1.26 alpine
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION=1.26
FROM golang:${GOLANG_VERSION}-alpine
LABEL maintainer="chinayin <whereismoney@qq.com>"
