#
#--------------------------------------------------------------------------
# golang 1.26 trixie
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION=1.26
FROM golang:${GOLANG_VERSION}-trixie
LABEL maintainer="chinayin <whereismoney@qq.com>"

COPY prebuildfs /
