#
#--------------------------------------------------------------------------
# golang 1.25 alpine
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}-alpine
LABEL maintainer="chinayin <whereismoney@qq.com>"
