#
#--------------------------------------------------------------------------
# golang 1.25 alpine
#--------------------------------------------------------------------------
#

ARG GOLANG_VERSION=1.25
FROM golang:${GOLANG_VERSION}-alpine
LABEL maintainer="chinayin <whereismoney@qq.com>"
